"""add_user_role_and_notifications

Revision ID: 1ff3075b3f12
Revises: 0003
Create Date: 2026-05-07 16:46:31.962547+00:00

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

# revision identifiers, used by Alembic.
revision = "1ff3075b3f12"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data"):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get("data"):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create userrole enum type
    userrole = postgresql.ENUM("ADMIN", "USER", name="userrole")
    userrole.create(op.get_bind())

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("ADMIN", "USER", name="userrole"),
            nullable=False,
            server_default="USER",
        ),
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.drop_table("notifications")

    # Drop userrole enum type
    userrole = postgresql.ENUM("ADMIN", "USER", name="userrole")
    userrole.drop(op.get_bind())
    # ### end Alembic commands ###


def data_upgrades():
    """Add optional data upgrade migrations here."""
    pass


def data_downgrades():
    """Add optional data downgrade migrations here."""
    pass
