"""change varchar length

Revision ID: cf93e56fe31b
Revises: 0001
Create Date: 2025-11-27 09:41:07.048810+00:00

"""

from alembic import op
import sqlalchemy as sa
from alembic import context

# revision identifiers, used by Alembic.
revision = "cf93e56fe31b"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data"):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get("data"):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contents",
        "description",
        existing_type=sa.VARCHAR(length=600),
        type_=sa.String(length=5000),
        existing_nullable=False,
    )
    op.alter_column(
        "youtubers",
        "description",
        existing_type=sa.VARCHAR(length=600),
        type_=sa.String(length=5000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "youtubers",
        "description",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=600),
        existing_nullable=False,
    )
    op.alter_column(
        "contents",
        "description",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=600),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def data_upgrades():
    """Add optional data upgrade migrations here."""
    pass


def data_downgrades():
    """Add optional data downgrade migrations here."""
    pass
