"""db_update

Revision ID: de23b17c566d
Revises: 1ff3075b3f12
Create Date: 2026-05-07 17:12:03.906207+00:00

"""

from alembic import context

# revision identifiers, used by Alembic.
revision = "de23b17c566d"
down_revision = "1ff3075b3f12"
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data"):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get("data"):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def data_upgrades():
    """Add optional data upgrade migrations here."""
    pass


def data_downgrades():
    """Add optional data downgrade migrations here."""
    pass
