from app.llm.protocols import ChatMessage, ChatServiceProtocol, RAGContext


class StubChatService(ChatServiceProtocol):

    DEMO_RESPONSES = [
        "This is a demo response from the stub chat service. In production, this would be generated by an LLM.",
        "Based on the provided context, here's what I found: The system is currently running in demo mode.",
        "Great question! The RAG context contains relevant information that helps answer this.",
        "I'm a stub service configured to return predefined responses for demonstration purposes.",
        "The context suggests this is a demo environment. In production, real LLM would process your query.",
    ]

    def __init__(self) -> None:
        self._response_index = 0

    async def chat(self, messages: list[ChatMessage]) -> str:
        return self._get_next_response()

    async def chat_with_rag(self, messages: list[ChatMessage], context: RAGContext) -> str:
        chunks_info = f" (from {len(context.chunks)} context chunks)" if context.chunks else ""
        return f"[STUB] Response with RAG context{chunks_info}. " + self._get_next_response()

    def _get_next_response(self) -> str:
        response = self.DEMO_RESPONSES[self._response_index % len(self.DEMO_RESPONSES)]
        self._response_index += 1
        return response


def get_chat_service() -> ChatServiceProtocol:
    # Resolve configuration at runtime from app.config.settings
    from app.config import settings
    demo_mode = getattr(settings, "demo_mode", False)
    if demo_mode:
        return StubChatService()
    from app.llm.chat_service import RealChatService
    return RealChatService()
